# Generated by Django 5.2.8 on 2026-02-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
    ]
