# Generated by Django 5.2.8 on 2026-02-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cover_image_source_url_alter_book_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_image_source_url',
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
