# Generated by Django 5.2.8 on 2026-01-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toread',
            name='finished_reading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='toread',
            name='reading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='toread',
            name='to_read',
            field=models.BooleanField(default=True),
        ),
    ]
