# Generated by Django 5.2.8 on 2025-12-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_info_link_book_publisher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
