# Generated by Django 5.2.8 on 2026-01-14 18:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_toread_finished_reading_toread_reading_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToRead',
            new_name='Library',
        ),
    ]
