# Generated by Django 5.2.8 on 2025-12-29 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewsummary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reviewsummary',
            name='is_generating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewsummary',
            name='last_summarized_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewsummary',
            name='reviews_added_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviewsummary',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_summary', to='books.book'),
        ),
        migrations.AlterField(
            model_name='reviewsummary',
            name='summary_text',
            field=models.CharField(max_length=400),
        ),
    ]
