# Generated by Django 5.2.8 on 2026-02-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_cover_image_source_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default='default_cover.png', upload_to='covers/'),
        ),
    ]
