# Generated by Django 5.2.8 on 2026-02-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='library',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='reviewsummary',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, related_name='book_authors', to='books.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default='default_book.png', upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='book_tags', to='books.tag'),
        ),
    ]
