# Generated by Django 5.2.8 on 2026-01-14 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_toread_library'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='only_rating',
        ),
    ]
