# Generated by Django 5.2.8 on 2025-12-29 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_reviewsummary_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='helpful_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name='ReviewHelpfulness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ReviewUpVote',
        ),
        migrations.AddIndex(
            model_name='reviewhelpfulness',
            index=models.Index(fields=['review'], name='books_revie_review__293200_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewhelpfulness',
            index=models.Index(fields=['user'], name='books_revie_user_id_2156c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewhelpfulness',
            constraint=models.UniqueConstraint(fields=('user', 'review'), name='uniq_user_review_helpful'),
        ),
    ]
