# Generated by Django 5.2.8 on 2026-01-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_review_only_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='finished_reading',
        ),
        migrations.RemoveField(
            model_name='library',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='library',
            name='reading',
        ),
        migrations.RemoveField(
            model_name='library',
            name='to_read',
        ),
        migrations.AddField(
            model_name='library',
            name='reading_status',
            field=models.CharField(choices=[('to_read', 'to_read'), ('in_progress', 'in_progress'), ('finished', 'finished')], default='to_read'),
        ),
    ]
