# Generated by Django 5.2.8 on 2026-02-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_author_updated_at_remove_library_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='info_link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
