# Generated by Django 5.2.8 on 2026-03-01 21:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_info_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reviewhelpfulness',
            name='uniq_user_review_helpful',
        ),
        migrations.RemoveIndex(
            model_name='reviewhelpfulness',
            name='books_revie_review__293200_idx',
        ),
        migrations.RemoveIndex(
            model_name='reviewhelpfulness',
            name='books_revie_user_id_2156c1_idx',
        ),
        migrations.AlterField(
            model_name='book',
            name='average_rating',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='reviews_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary_generated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['book', '-helpful_count', '-inserted_at'], name='books_revie_book_id_9c14cf_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewhelpfulness',
            index=models.Index(fields=['review', 'user'], name='books_revie_review__a51cee_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewhelpfulness',
            constraint=models.UniqueConstraint(fields=('user', 'review'), name='unique_user_review_helpful'),
        ),
    ]
