# Generated by Django 5.2.8 on 2025-12-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
