# Generated by Django 5.2.8 on 2026-03-02 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_reviewhelpfulness_uniq_user_review_helpful_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_imported',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('is_imported', False)), fields=('book', 'user'), name='uniq_user_review_except_imported'),
        ),
    ]
