# Generated by Django 5.2.8 on 2026-01-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsummary',
            name='last_summarized_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='reviewsummary',
            name='reviews_added_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='reviewsummary',
            name='summary_text',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
