# Generated by Django 5.2.8 on 2026-01-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_reviewsummary_last_summarized_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reviews_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviewsummary',
            name='last_summarized_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviewsummary',
            name='reviews_added_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
