# Generated by Django 5.2.8 on 2026-01-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_reviews_counts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='reviews_counts',
            new_name='reviews_count',
        ),
    ]
