# Generated by Django 5.2.8 on 2026-01-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_rename_reviews_counts_book_reviews_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsummary',
            name='summary_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
